### ISSUE TITLE
ocamlfind.exe command not found despite exists

### ISSUE THREAD

**Issue by multidecay** [diskuv/dkml-installer-ocaml#100]
Oh, hello there.

Let me reporting some weird behaviour of my ocaml installation. Currently, I tried to compiled LLVM in my cmoputter and wanted to enabled OCaml LLVM bindings for it, but 

It says:

```
FATAL: C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe: no such command in PATH
FATAL: C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe: no such command in PATH
FATAL: C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe: no such command in PATH
-- Could NOT find OCaml (missing: OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
```

I got the same as `FATAL` message when I run it directly with `C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe` , but it work well when `C:\Users\[username]\AppData\Local\Programs\DkMLNative\bin\ocamlfind.exe`. I guess the culpirt is with path finding.

Is correct that `ocamlfind.exe` call `ocamlfind-real.exe` ? because I swap the `.exe` and get `Z:/sources...` error, I didn't have Z: drive on my putter though.

```
ocamlfind: Config file not found - neither Z:\source\dkml\build\pkg\bump\.ci\o\PT\lib\findlib.conf nor the directory Z:\source\dkml\build\pkg\bump\.ci\o\PT\lib\findlib.conf.d
ocamlfind: Config file not found - neither Z:\source\dkml\build\pkg\bump\.ci\o\PT\lib\findlib.conf nor the directory Z:\source\dkml\build\pkg\bump\.ci\o\PT\lib\findlib.conf.d
ocamlfind: Config file not found - neither Z:\source\dkml\build\pkg\bump\.ci\o\PT\lib\findlib.conf nor the directory Z:\source\dkml\build\pkg\bump\.ci\o\PT\lib\findlib.conf.d
-- Could NOT find OCaml (missing: OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
```

Thank you.

**Comment by jonahbeckford** [comment]
> Is correct that ocamlfind.exe call ocamlfind-real.exe ? because I swap the .exe and get Z:/sources... error, I didn't have Z: drive on my putter though.

That seems irrelevant to your problem. If you can run it from the command line in normal Windows syntax (\ backslashes), but not in Unix syntax (/ forward slashes), then the problem is with the OCaml LLVM build scripts not using or not searching with the correct syntax on Windows.

You’ll want to open a ticket with OCaml LLVM.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ΧΗΠ ***@***.***>
Sent: Saturday, March 9, 2024 5:43:20 PM
To: diskuv/dkml-installer-ocaml ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [diskuv/dkml-installer-ocaml] ocamlfind.exe not command found despite exists (Issue #100)


Oh, hello there.

Let me reporting some weird behaviour of my ocaml installation. Currently, I tried to compiled LLVM in my cmoputter and wanted to enabled OCaml LLVM bindings for it, but

It says:

FATAL: C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe: no such command in PATH
FATAL: C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe: no such command in PATH
FATAL: C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe: no such command in PATH
-- Could NOT find OCaml (missing: OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.


I got the same as FATAL message when I run it directly with C:/Users/[username]/AppData/Local/Programs/DkMLNative/bin/ocamlfind.exe , but it work well when C:\Users\[username]\AppData\Local\Programs\DkMLNative\bin\ocamlfind.exe. I guess the is with path finding.

Is correct that ocamlfind.exe call ocamlfind-real.exe ? because I swap the .exe and get Z:/sources... error, I didn't have Z: drive on my putter though.

Thank you.

**Comment by multidecay** [comment]
I doubt that. In the CMake procces all binary that subjected with unix syntax works fine except the ocaml binary that have `-real.exe` counterpart.

```
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
-- Found Python3: C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0/python3.11.exe (found suitable version "3.11.8", minimum required is "3.6") found components: Interpreter
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/ml64.exe
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.37.3.windows.1")
```

Here the execution:
![ocaml-real-exe-conjecture](https://github.com/diskuv/dkml-installer-ocaml/assets/45910674/de5b9175-4f94-4924-bc63-9f26fc9a901b)

**Comment by multidecay** [comment]
I think this issue not worth. I just learn the OCaml binding could build separately from LLVM build process. 

Anyway, thank you for making this piece of software, I could code OCaml in windows.
