### ISSUE TITLE
Recovering from network failures

### ISSUE THREAD

**Issue by ysalmon** [diskuv/dkml-installer-ocaml#37]
I cannot proceed to the initial installation because the installer reports that the Git for Windows installer is corrupted :

```
The Git for Windows installer was corrupted. You will need to retry the installation. If this repeatedly occurs,
please send an email to support@diskuv.com
Au caractère
C:\Users\yann\AppData\Local\Temp\7zC98A7834\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1:658 : 13
+             throw "The Git for Windows installer was corrupted. You w ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The Git for Win...port@diskuv.com:String) [], RuntimeException
    + FullyQualifiedErrorId : The Git for Windows installer was corrupted. You will need to retry the installation. If
    this repeatedly occurs, please send an email to support@diskuv.com

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\yann\AppData\Local\Temp\7zC98A7834\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\yann\AppData\Local\Programs\DISKUV~1
                                             -MSYS2Dir
                                             C:\Users\yann\AppData\Local\Programs\DISKUV~1\tools\MSYS2
                                             -OpamExe
                                             C:\Users\yann\AppData\Local\Programs\DISKUV~1\bin\OPAM-R~1.EXE
                                             -DkmlPath
                                             C:\Users\yann\AppData\Local\Temp\7ZC98A~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -GlobalCompileDir
                                             C:\Users\yann\AppData\Local\Temp\7ZC98A~1\sg\STAGIN~1\generic
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\yann\AppData\Local\Temp\PA319F~1
                                             -SkipProgress -SkipMSYS2Update
                                             -ImpreciseC99FloatOps

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\yann\AppData\Local\Temp\7zC98A7834\bin\dkml-install-user-runner.exe
                                         install-user-network-ocamlcompiler --verbosity=info
                                         --color=always --prefix
                                         C:\Users\yann\AppData\Local\Programs\DiskuvOCaml
                                         --staging-files
                                         C:\Users\yann\AppData\Local\Temp\7zC98A7834\sg

                         >>> A transient failure occurred. <<<
```

**Comment by ysalmon** [comment]
A workaround seems to be installing Git for Windows manually beforehand.

**Comment by jonahbeckford** [comment]
Yikes. Thanks for reporting.

**Comment by jonahbeckford** [comment]
I double-checked that the current download (https://github.com/git-for-windows/git/releases/download/v2.36.1.windows.1/Git-2.36.1-64-bit.exe) does match the expected checksum (`08A0C20374D13D1B448D2C5713222FF55DD1F4BFFA15093B85772CC0FC5F30E7`).

I won't be able to investigate why your download was corrupted ... but it sounds like the SHA256 checksum verification did its job! This is one of the few times where we know the DKML installer is right. It could be a zillion other things: the download had a bit flip during transit (rare), the download site was down temporarily and gave a generic 503 HTML page (not rare at all, especially for GitHub), the download site was compromised temporarily (I've seen it happen, but rare), you have an aggressive malware checker that quarantines or modifies executables in place (not rare), you have a flaky network proxy (you would know), you have something on your machine that can intercept `Invoke-WebRequest` or PowerShell, etc. If you suspect this is not transient, you can investigate further by doing the following in PowerShell:

```powershell
$GitWindowsSetupAbsPath = $env:TEMP

# Then copy and paste the lines from
# https://github.com/diskuv/dkml-component-ocamlcompiler/blob/e13977b3c1df32433ca6b2dea1c71a86e33aa5ca/assets/staging-files/win32/setup-userprofile.ps1#L642-L659
```

The real bug is not being able to retry the installation ... as the message tells you ... without using the uninstaller. You have #36 already open for that.

I'll close this after #36 is addressed.

**Comment by ysalmon** [comment]
Thanks you for looking into that. Indeed, download failures can happen. What surprises me is that it happened several times. It is really a case of bad luck that github would have had problems for several minutes in a row.

Anyway, running the commands in powershell now gives no error.

Maybe the installer could offer to retry the download in such a case, instead of crashing, and the user having to restart from zero (see my comment on #36).

**Comment by jonahbeckford** [comment]
> It is really a case of bad luck that github would have had problems for several minutes in a row.

The actual 99% likely situation is ... if all the download problems were GitHub URLs ... is that GitHub is throttling your external IP address, not that they are having an outage. If you share your external IP address with others (do you?), you can be retrying for quite a while before the rate limiting is removed. And we'd have to patch `opam.exe` to ask the users for retries as well, because near the end of the installer `opam.exe install` dominates the time.

Regardless, Microsoft does not allow packages to be submitted to `winget install` if the package does not have a mode where no questions are asked (silent install). We have to get clean installs without prompting.

I think I answered a question for myself. I don't see any recourse except to bundle the Git for Windows installer and any subsequent downloads into the installer. I did that for MSYS2 the last release cycle. Bundling Git for Windows will add an extra 100GB to the installer; that should be fine. And I'd have to figure out a way to pre-bundle the opam repositories (in an idempotent way, one that respects any subsequent `opam update`; perhaps a pre-populated cache).

I'll change the title of this issue and keep it open. But it won't be the highest priority because waiting (if you are rate limited) or retrying (if it is a transient outage) are workarounds.

**Comment by ysalmon** [comment]
I do not think I share my IP address ; this is my home connection and I am alone on it.

> Regardless, Microsoft does not allow packages to be submitted to winget install if the package does not have a mode where no questions are asked (silent install). We have to get clean installs without prompting.

Does Diskuv have a interactive mode too ?

> an extra 100GB to the installer

That seems a lot.

**Comment by jonahbeckford** [comment]
You have a dedicated external IP on your _home connection_? That is rare in the United States; typically the ISPs will rotate home IP addresses frequently. I had to search for an ISP that only does that on average once a month. (Also, home connections are the least reliable network connections, at least where I am from. But I'm guessing you are pretty advanced in your home networking setup so I won't talk about networking anymore.)

I have limited resources, and do not think that adding interactivity to muddle through rare (as far as I know) network issues is a good use of those limited resources. Doing a basic [`Invoke-WebRequest`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.3) should not fail and should not need to be retried on top of the Microsoft defaults. I especially don't think asking interactive questions for every network connection is a good use of resources when adding GBs to an installer permanently solves the problem, and when that "offline" feature has been requested by others.

Not sure if I can convince you, but I have to balance interests for all users.

**Comment by ysalmon** [comment]
The configuration interface from my ISP has a specific button to allow me to request a change in my IP address, so I think it is dedicated and will not change without request. It is a FTTH connection and has been very reliable.

I understand it would be a hassle to add checks and retries everywhere. And the problem becomes moot if we can effectively re-run the whole installer (which I understand is intended to be possible, but currently is not, because of the error on the file renaming step in #36).

**Comment by jonahbeckford** [comment]
Closing because related #36 was closed
