### ISSUE TITLE
Cannot create switch to mounted newtork drive

### ISSUE THREAD

**Issue by ysalmon** [diskuv/dkml-installer-ocaml#42]
I managed to install the prerelease of Diskuv OCaml.

When I say ``opam switch create k:\\OCaml 5.0.0``, where ``k:`` is a network drive mounted to a UNC server, things actually happen in ``C:\\Users\\yann\\UNC\\VBOXSVR\\MVshare\\OCaml``, and nothing is written to ``k:`` (compilation fails because "flexlink does not work", but that is another issue).

The opam installation from [fdopen](https://fdopen.github.io/opam-repository-mingw/installation/) did not exhibit this behaviour.

**Comment by jonahbeckford** [comment]
The UNC server bug is unrelated to Diskuv OCaml. You aren't seeing anything with fdopen because it does not use the newer Opam 2.2. You'll need to file a bug with https://github.com/ocaml/opam and make sure to report your `opam --version` in it.

By the way:
* 5.0.0 will not work with Diskuv OCaml or any MSVC system. The OCaml team will announce when that is ready. Don't expect full support for MSVC until 5.1 or 5.2.
* The only supported way to create local switches in Diskuv OCaml is `dkml init`. That is described in some detail on https://diskuv-ocaml.gitlab.io/distributions/dkml/doc/BeyondBasics.html
