### ISSUE TITLE
A transient failure occurred

### ISSUE THREAD

**Issue by houdelou** [diskuv/dkml-installer-ocaml#55]
I tried to install OCaml with Diskuv on Windows 10. The installation failed. Here is the log and output attached.
[output.log](https://github.com/diskuv/dkml-installer-ocaml/files/12022844/output.log)
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/12022845/setup-userprofile.full.log)

**Comment by jonahbeckford** [comment]
Looks like you are running in a virtual environment.

checking whether fma works... no
configure: error: fma does not work, enable emulation with --enable-imprecise-c99-float-ops

**Comment by jonahbeckford** [comment]
Follow the instructions at https://github.com/diskuv/dkml-installer-ocaml/issues/27 to fix it

**Comment by houdelou** [comment]
Thanks ! works perfectly. I was not running in a VM though.

**Comment by jonahbeckford** [comment]
We have to compile because OCaml is not relocatable. Here is one thread that discusses it: https://discuss.ocaml.org/t/relocatable-compiler-work/11218

Basically, all OCaml executables have hardcoded library paths in them. This isn't a problem usually on Linux because you can pre-generate OCaml executables as `/usr/bin/ocaml` (etc.) and those executables can be deployed in the same path. That doesn't work for Windows of course unless we hardcode the "C:" drive and hardcode a directory and require every Windows user to be an Administrator.

**Comment by houdelou** [comment]
It is indeed a complex topic. You did a great job. Once installed, it works really well. I'm very happy that Windows is taken into account. I'm realy starting to like the language and platform and looking forward to contribute when I'll be more experienced. Thanks for your help !

**Comment by houdelou** [comment]
@jonahbeckford fyi, I opened an issue for sqlite3 opam package because when I try to install it, I get error "pkg-config" not found. So I looked in msys installation published with the ocaml installer and the command is not there. I installed it with pacman and now I get another error at pkg-config step. This information might interest you.

**Comment by jonahbeckford** [comment]
Can you post a link to the issue? I definitely want sqlite3 to work on Windows and will probably look at that soon.

**Comment by houdelou** [comment]
https://github.com/ocaml/opam-repository/issues/24136

**Comment by jonahbeckford** [comment]
Created issue at https://github.com/diskuv/dkml-installer-ocaml/issues/57
