### ISSUE TITLE
FATAL: No Common7/Tools/VsDevCmd.bat was detected at /c/DiskuvOCaml/BuildTools

### ISSUE THREAD

**Issue by useada** [diskuv/dkml-installer-ocaml#61]
I want to update DkML from version 1.2.0 to 2.0.2, but i made a mistake that i just removed the old folders “C:\DiskuvOCaml” and “C:\Users**\AppData\Local\Programs\DiskuvOCaml”.

When I run then setup command “setup64nu.exe”, it got the errors:

```
[2023-08-19T01:43:15+00:00] git -C C:/Users/usead/AppData/Local/Programs/DKMLNA~1/src/ocaml submodule update --init --recursive
Submodule 'flexdll' (https://github.com/alainfrisch/flexdll.git) registered for path 'flexdll'
Cloning into 'C:/Users/usead/AppData/Local/Programs/DkMLNative/src/ocaml/flexdll'...
Submodule path 'flexdll': checked out 'f624a8a94867f616715bf95764466959bbc67a28'
[2023-08-19T01:43:19+00:00] /usr/bin/chmod
[2023-08-19T01:43:37+00:00] git -C C:/Users/usead/AppData/Local/Programs/DKMLNA~1/src/ocaml clean -d -x -f
[2023-08-19T01:43:37+00:00] git -C C:/Users/usead/AppData/Local/Programs/DKMLNA~1/src/ocaml submodule foreach --recursive git clean -d -x -f -
Entering 'flexdll'
FATAL: No Common7/Tools/VsDevCmd.bat was detected at /c/DiskuvOCaml/BuildTools
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: C:\Users\usead\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 MSYSTEM_CARCH=x86_64 MSYSTEM_CHOST=x86_64-w64-mingw32 MINGW_CHOST=x86_64-w64-mingw32 MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64 MINGW_PREFIX=/clang64 HOME=/home/usead PATH=/clang64/bin:/usr/bin:/bin C:\Users\usead\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/usead/AppData/Local/Temp/PAF590~1/0 env DiskuvOCamlVarsVersion=2 DiskuvOCamlDeploymentId='v-2.0.2;ocaml-4.14.0;opam-2.2.0~alpha0~20221228;msys2-F45581C12EA79770' DiskuvOCamlVersion='2.0.2' DiskuvOCamlMode='native' DiskuvOCamlHome='/c/Users/usead/AppData/Local/Programs/DKMLNA~1' DiskuvOCamlBinaryPaths='/c/Users/usead/AppData/Local/Programs/DKMLNA~1/usr/bin;/c/Users/usead/AppData/Local/Programs/DKMLNA~1/bin' DiskuvOCamlMSYS2Dir='/' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/usead/AppData/Local/Temp/7Z6CAC~1/sg/OCAMLC~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop C:\Users\usead\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\sh.exe /c/Users/usead/AppData/Local/Temp/7z6CAC92AC/sg/ocamlcompiler-common/windows_x86_64/install-ocaml.sh /c/Users/usead/AppData/Local/Temp/7Z6CAC~1/sg/OCAMLC~1/WINDOW~1/dkmldir 15553b77175270d987058b386d737ccb939e8d5a windows_x86_64 /c/Users/usead/AppData/Local/Programs/DKMLNA~1 --disable-imprecise-c99-float-ops

at Invoke-MSYS2Command, C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 180
at Invoke-GenericCommandWithProgress, C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 841
at <ScriptBlock>, C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 1156
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1



[Advanced] MSYS2 commands can be run with: C:\Users\usead\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\msys2_shell.cmd


Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\usead\AppData\Local\Programs\DKMLNA~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\usead\AppData\Local\Programs\DKMLNA~1
                                             -OCamlLangVersion 4.14.0
                                             -DkmlPath
                                             C:\Users\usead\AppData\Local\Temp\7Z6CAC~1\sg\OCAMLC~1\WINDOW~1\dkmldir
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\usead\AppData\Local\Temp\PAF590~1
                                             -SkipProgress -SkipMSYS2Update
                                             -OpamExe
                                             C:\Users\usead\AppData\Local\Programs\DKMLNA~1\bin\OPAM-R~1.EXE
                                             -MSYS2Dir
                                             C:\Users\usead\AppData\Local\Programs\DKMLNA~1\tools\MSYS2

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\bin\dkml-install-user-runner.exe
                                         install-user-ocamlcompiler-network --verbosity=info
                                         --color=always --prefix
                                         C:\Users\usead\AppData\Local\Programs\DkMLNative
                                         --staging-files
                                         C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg

                         >>> A transient failure occurred. <<<



Press "y" and ENTER to exit the installer.

```

**Comment by jonahbeckford** [comment]
Not sure if you can recover easily from the state you are in. The C:\DiskuvOCaml directory is the problem... that is controlled by the Visual Studio Installer.

Try running the Visual Studio Installer (Windows key ... then type Visual Studio Installer). It should have a Repair option near each installation it knows about. I would do a Repair first, and then do a Remove (all from within the Visual Studio Installer) to hopefully get back to a good state.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: useada ***@***.***>
Sent: Sunday, August 20, 2023 8:46 PM
To: diskuv/dkml-installer-ocaml ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [diskuv/dkml-installer-ocaml] FATAL: No Common7/Tools/VsDevCmd.bat was detected at /c/DiskuvOCaml/BuildTools (Issue #61)


I want to update DkML from version 1.2.0 to 2.0.2, but i made a mistake that i just removed the old folders “C:\DiskuvOCaml” and “C:\Users**\AppData\Local\Programs\DiskuvOCaml”.

When I run then setup command “setup64nu.exe”, it got the errors:

`
[2023-08-19T01:43:15+00:00] git -C C:/Users/usead/AppData/Local/Programs/DKMLNA1/src/ocaml submodule update --init --recursive
Submodule 'flexdll' (https://github.com/alainfrisch/flexdll.git) registered for path 'flexdll'
Cloning into 'C:/Users/usead/AppData/Local/Programs/DkMLNative/src/ocaml/flexdll'...
Submodule path 'flexdll': checked out 'f624a8a94867f616715bf95764466959bbc67a28'
[2023-08-19T01:43:19+00:00] /usr/bin/chmod
[2023-08-19T01:43:37+00:00] git -C C:/Users/usead/AppData/Local/Programs/DKMLNA1/src/ocaml clean -d -x -f
[2023-08-19T01:43:37+00:00] git -C C:/Users/usead/AppData/Local/Programs/DKMLNA1/src/ocaml submodule foreach --recursive git clean -d -x -f -
Entering 'flexdll'
FATAL: No Common7/Tools/VsDevCmd.bat was detected at /c/DiskuvOCaml/BuildTools
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: C:\Users\usead\AppData\Local\Programs\DKMLNA1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 MSYSTEM_CARCH=x86_64 MSYSTEM_CHOST=x86_64-w64-mingw32 MINGW_CHOST=x86_64-w64-mingw32 MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64 MINGW_PREFIX=/clang64 HOME=/home/usead PATH=/clang64/bin:/usr/bin:/bin C:\Users\usead\AppData\Local\Programs\DKMLNA1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/usead/AppData/Local/Temp/PAF5901/0 env DiskuvOCamlVarsVersion=2 DiskuvOCamlDeploymentId='v-2.0.2;ocaml-4.14.0;opam-2.2.0alpha020221228;msys2-F45581C12EA79770' DiskuvOCamlVersion='2.0.2' DiskuvOCamlMode='native' DiskuvOCamlHome='/c/Users/usead/AppData/Local/Programs/DKMLNA1' DiskuvOCamlBinaryPaths='/c/Users/usead/AppData/Local/Programs/DKMLNA1/usr/bin;/c/Users/usead/AppData/Local/Programs/DKMLNA1/bin' DiskuvOCamlMSYS2Dir='/' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/usead/AppData/Local/Temp/7Z6CAC1/sg/OCAMLC1/WINDOW1/dkmldir/vendor/drc/all/emptytop C:\Users\usead\AppData\Local\Programs\DKMLNA1\tools\MSYS2\usr\bin\sh.exe /c/Users/usead/AppData/Local/Temp/7z6CAC92AC/sg/ocamlcompiler-common/windows_x86_64/install-ocaml.sh /c/Users/usead/AppData/Local/Temp/7Z6CAC1/sg/OCAMLC1/WINDOW1/dkmldir 15553b77175270d987058b386d737ccb939e8d5a windows_x86_64 /c/Users/usead/AppData/Local/Programs/DKMLNA~1 --disable-imprecise-c99-float-ops

at Invoke-MSYS2Command, C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 180
at Invoke-GenericCommandWithProgress, C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 841
at , C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 1156
at , : line 1
at , : line 1

[Advanced] MSYS2 commands can be run with: C:\Users\usead\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
C:\Users\usead\AppData\Local\Programs\DKMLNA~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.bat
-AllowRunAsAdmin
-InstallationPrefix
C:\Users\usead\AppData\Local\Programs\DKMLNA1
-OCamlLangVersion 4.14.0
-DkmlPath
C:\Users\usead\AppData\Local\Temp\7Z6CAC1\sg\OCAMLC1\WINDOW1\dkmldir
-NoDeploymentSlot -DkmlHostAbi
windows_x86_64 -TempParentPath
C:\Users\usead\AppData\Local\Temp\PAF5901
-SkipProgress -SkipMSYS2Update
-OpamExe
C:\Users\usead\AppData\Local\Programs\DKMLNA1\bin\OPAM-R1.EXE
-MSYS2Dir
C:\Users\usead\AppData\Local\Programs\DKMLNA1\tools\MSYS2

A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
A transient failure occurred.

                     Root cause: The command had exit code 20:
                                   C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\bin\dkml-install-user-runner.exe
                                     install-user-ocamlcompiler-network --verbosity=info
                                     --color=always --prefix
                                     C:\Users\usead\AppData\Local\Programs\DkMLNative
                                     --staging-files
                                     C:\Users\usead\AppData\Local\Temp\7z6CAC92AC\sg

                     >>> A transient failure occurred. <<<


Press "y" and ENTER to exit the installer.

`

**Comment by jonahbeckford** [comment]
np.
