### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Pobedinsky** [diskuv/dkml-installer-ocaml#69]
Entering 'flexdll'
/c/Users/artur/AppData/Local/Temp/7ZDDAF~1/sg/OCAMLC~1/WINDOW~1/dkmldir/vendor/drc/unix/crossplatform-functions.sh: line 2513: /usr/bin/awk: Permission denied
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 126. Command was: C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 MSYSTEM_CARCH=x86_64 MSYSTEM_CHOST=x86_64-w64-mingw32 MINGW_CHOST=x86_64-w64-mingw32 MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64 MINGW_PREFIX=/clang64 HOME=/home/artur PATH=/clang64/bin:/usr/bin:/bin C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/artur/AppData/Local/Temp/PAAF54~1/0 env DiskuvOCamlVarsVersion=2 DiskuvOCamlDeploymentId='v-2.0.3;ocaml-4.14.0;opam-2.2.0~alpha0~20221228;msys2-F45581C12EA79770' DiskuvOCamlVersion='2.0.3' DiskuvOCamlMode='native' DiskuvOCamlHome='/c/Users/artur/AppData/Local/Programs/DKMLNA~1' DiskuvOCamlBinaryPaths='/c/Users/artur/AppData/Local/Programs/DKMLNA~1/usr/bin;/c/Users/artur/AppData/Local/Programs/DKMLNA~1/bin' DiskuvOCamlMSYS2Dir='/' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/artur/AppData/Local/Temp/7ZDDAF~1/sg/OCAMLC~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\sh.exe /c/Users/artur/AppData/Local/Temp/7zDDAF5798/sg/ocamlcompiler-common/windows_x86_64/install-ocaml.sh /c/Users/artur/AppData/Local/Temp/7ZDDAF~1/sg/OCAMLC~1/WINDOW~1/dkmldir 15553b77175270d987058b386d737ccb939e8d5a windows_x86_64 /c/Users/artur/AppData/Local/Programs/DKMLNA~1 --disable-imprecise-c99-float-ops

at Invoke-MSYS2Command, C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 180
at Invoke-GenericCommandWithProgress, C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 841
at <ScriptBlock>, C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 1156
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

[Advanced] MSYS2 commands can be run with: C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\artur\AppData\Local\Programs\DKMLNA~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\artur\AppData\Local\Programs\DKMLNA~1
                                             -OCamlLangVersion 4.14.0
                                             -DkmlPath
                                             C:\Users\artur\AppData\Local\Temp\7ZDDAF~1\sg\OCAMLC~1\WINDOW~1\dkmldir
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\artur\AppData\Local\Temp\PAAF54~1
                                             -SkipProgress -SkipMSYS2Update
                                             -OpamExe
                                             C:\Users\artur\AppData\Local\Programs\DKMLNA~1\bin\OPAM-R~1.EXE
                                             -MSYS2Dir
                                             C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\artur\AppData\Local\Temp\7zDDAF5798\bin\dkml-install-user-runner.exe
                                         install-user-ocamlcompiler-network --verbosity=info
                                         --color=always --prefix
                                         C:\Users\artur\AppData\Local\Programs\DkMLNative
                                         --staging-files
                                         C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg

                         >>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
Can you try with your anti-virus and malware software temporarily disabled during installation? Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Max Pobedinsky ***@***.***>
Sent: Friday, September 15, 2023 7:02:16 PM
To: diskuv/dkml-installer-ocaml ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [diskuv/dkml-installer-ocaml] Permission denied  (Issue #69)


Entering 'flexdll'
/c/Users/artur/AppData/Local/Temp/7ZDDAF1/sg/OCAMLC1/WINDOW1/dkmldir/vendor/drc/unix/crossplatform-functions.sh: line 2513: /usr/bin/awk: Permission denied
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 126. Command was: C:\Users\artur\AppData\Local\Programs\DKMLNA1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 MSYSTEM_CARCH=x86_64 MSYSTEM_CHOST=x86_64-w64-mingw32 MINGW_CHOST=x86_64-w64-mingw32 MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64 MINGW_PREFIX=/clang64 HOME=/home/artur PATH=/clang64/bin:/usr/bin:/bin C:\Users\artur\AppData\Local\Programs\DKMLNA1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/artur/AppData/Local/Temp/PAAF541/0 env DiskuvOCamlVarsVersion=2 DiskuvOCamlDeploymentId='v-2.0.3;ocaml-4.14.0;opam-2.2.0alpha020221228;msys2-F45581C12EA79770' DiskuvOCamlVersion='2.0.3' DiskuvOCamlMode='native' DiskuvOCamlHome='/c/Users/artur/AppData/Local/Programs/DKMLNA1' DiskuvOCamlBinaryPaths='/c/Users/artur/AppData/Local/Programs/DKMLNA1/usr/bin;/c/Users/artur/AppData/Local/Programs/DKMLNA1/bin' DiskuvOCamlMSYS2Dir='/' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/artur/AppData/Local/Temp/7ZDDAF1/sg/OCAMLC1/WINDOW1/dkmldir/vendor/drc/all/emptytop C:\Users\artur\AppData\Local\Programs\DKMLNA1\tools\MSYS2\usr\bin\sh.exe /c/Users/artur/AppData/Local/Temp/7zDDAF5798/sg/ocamlcompiler-common/windows_x86_64/install-ocaml.sh /c/Users/artur/AppData/Local/Temp/7ZDDAF1/sg/OCAMLC1/WINDOW1/dkmldir 15553b77175270d987058b386d737ccb939e8d5a windows_x86_64 /c/Users/artur/AppData/Local/Programs/DKMLNA~1 --disable-imprecise-c99-float-ops

at Invoke-MSYS2Command, C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 180
at Invoke-GenericCommandWithProgress, C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 841
at , C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 1156
at , : line 1
at , : line 1

[Advanced] MSYS2 commands can be run with: C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
C:\Users\artur\AppData\Local\Programs\DKMLNA~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.bat
-AllowRunAsAdmin
-InstallationPrefix
C:\Users\artur\AppData\Local\Programs\DKMLNA1
-OCamlLangVersion 4.14.0
-DkmlPath
C:\Users\artur\AppData\Local\Temp\7ZDDAF1\sg\OCAMLC1\WINDOW1\dkmldir
-NoDeploymentSlot -DkmlHostAbi
windows_x86_64 -TempParentPath
C:\Users\artur\AppData\Local\Temp\PAAF541
-SkipProgress -SkipMSYS2Update
-OpamExe
C:\Users\artur\AppData\Local\Programs\DKMLNA1\bin\OPAM-R1.EXE
-MSYS2Dir
C:\Users\artur\AppData\Local\Programs\DKMLNA1\tools\MSYS2

A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
A transient failure occurred.

                     Root cause: The command had exit code 20:
                                   C:\Users\artur\AppData\Local\Temp\7zDDAF5798\bin\dkml-install-user-runner.exe
                                     install-user-ocamlcompiler-network --verbosity=info
                                     --color=always --prefix
                                     C:\Users\artur\AppData\Local\Programs\DkMLNative
                                     --staging-files
                                     C:\Users\artur\AppData\Local\Temp\7zDDAF5798\sg

**Comment by Pobedinsky** [comment]
The error continues, i run it as administrator and disabled AVAST shields:                                                                         
Everything is Ok
windows_install.bc: [INFO] C:\Users\artur\AppData\Local\Temp\7z8FD92D88\sg\offline-unixutils\windows_x86_64\bin\msys2-base.sfx.exe ran successfully with exit code 0
FATAL [54c34807]. move C:\Users\artur\AppData\Local\Programs\DkMLNative\tools\msys64 to C:\Users\artur\AppData\Local\Programs\DkMLNative\tools\MSYS2: Permission denied

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\artur\AppData\Local\Temp\7z8FD92D88\bin\dkml-install-user-runner.exe
                                         install-user-offline-unixutils --verbosity=info
                                         --color=always --prefix
                                         C:\Users\artur\AppData\Local\Programs\DkMLNative
                                         --staging-files
                                         C:\Users\artur\AppData\Local\Temp\7z8FD92D88\sg

                         >>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
That is not the same error.

Because of a [known bug with the `2.0.3` uninstaller](https://github.com/diskuv/dkml-installer-ocaml/issues/67), I should have told you to manually uninstall before trying to re-install. Please manually uninstall first by doing:

1. Delete `C:\Users\artur\AppData\Local\Programs\DiskuvOCaml`
2. Delete `C:\Users\artur\AppData\Local\Programs\DkMLNative`

Then please try the installation again with AVAST shield disabled.

**Comment by Pobedinsky** [comment]
Right, so i got again the same error:                                                                                                                                                                             Entering 'flexdll'
/c/Users/artur/AppData/Local/Temp/7ZDFA6~1/sg/OCAMLC~1/WINDOW~1/dkmldir/vendor/drc/unix/crossplatform-functions.sh: line 2513: /usr/bin/awk: Permission denied
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 126. Command was: C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 MSYSTEM_CARCH=x86_64 MSYSTEM_CHOST=x86_64-w64-mingw32 MINGW_CHOST=x86_64-w64-mingw32 MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64 MINGW_PREFIX=/clang64 HOME=/home/artur PATH=/clang64/bin:/usr/bin:/bin C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/artur/AppData/Local/Temp/PA8F15~1/0 env DiskuvOCamlVarsVersion=2 DiskuvOCamlDeploymentId='v-2.0.3;ocaml-4.14.0;opam-2.2.0~alpha0~20221228;msys2-F45581C12EA79770' DiskuvOCamlVersion='2.0.3' DiskuvOCamlMode='native' DiskuvOCamlHome='/c/Users/artur/AppData/Local/Programs/DKMLNA~1' DiskuvOCamlBinaryPaths='/c/Users/artur/AppData/Local/Programs/DKMLNA~1/usr/bin;/c/Users/artur/AppData/Local/Programs/DKMLNA~1/bin' DiskuvOCamlMSYS2Dir='/' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/artur/AppData/Local/Temp/7ZDFA6~1/sg/OCAMLC~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\sh.exe /c/Users/artur/AppData/Local/Temp/7zDFA67200/sg/ocamlcompiler-common/windows_x86_64/install-ocaml.sh /c/Users/artur/AppData/Local/Temp/7ZDFA6~1/sg/OCAMLC~1/WINDOW~1/dkmldir 15553b77175270d987058b386d737ccb939e8d5a windows_x86_64 /c/Users/artur/AppData/Local/Programs/DKMLNA~1 --disable-imprecise-c99-float-ops

at Invoke-MSYS2Command, C:\Users\artur\AppData\Local\Temp\7zDFA67200\sg\ocamlcompiler-common\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 180
at Invoke-GenericCommandWithProgress, C:\Users\artur\AppData\Local\Temp\7zDFA67200\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 841
at <ScriptBlock>, C:\Users\artur\AppData\Local\Temp\7zDFA67200\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 1156
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1



[Advanced] MSYS2 commands can be run with: C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\msys2_shell.cmd


Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\artur\AppData\Local\Programs\DKMLNA~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\artur\AppData\Local\Temp\7zDFA67200\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\artur\AppData\Local\Programs\DKMLNA~1
                                             -OCamlLangVersion 4.14.0
                                             -DkmlPath
                                             C:\Users\artur\AppData\Local\Temp\7ZDFA6~1\sg\OCAMLC~1\WINDOW~1\dkmldir
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\artur\AppData\Local\Temp\PA8F15~1
                                             -SkipProgress -SkipMSYS2Update
                                             -OpamExe
                                             C:\Users\artur\AppData\Local\Programs\DKMLNA~1\bin\OPAM-R~1.EXE
                                             -MSYS2Dir
                                             C:\Users\artur\AppData\Local\Programs\DKMLNA~1\tools\MSYS2

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\artur\AppData\Local\Temp\7zDFA67200\bin\dkml-install-user-runner.exe
                                         install-user-ocamlcompiler-network --verbosity=info
                                         --color=always --prefix
                                         C:\Users\artur\AppData\Local\Programs\DkMLNative
                                         --staging-files
                                         C:\Users\artur\AppData\Local\Temp\7zDFA67200\sg

                         >>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
Something else interfering on your machine ... but I'll have to setup a Zoom session with you to figure that out.

Are you available in 30 minutes or so?

**Comment by jonahbeckford** [comment]
If not, you can pick a spot on https://calendly.com/diskuv/30-minute-dkml-installation?back=1&month=2023-09

**Comment by Pobedinsky** [comment]
thank you, nvm, i will use it on linux

**Comment by jonahbeckford** [comment]
Okay.
